services:
  backend:
    build: ./serveur
    container_name: php_backend
    restart: unless-stopped
    volumes:
      - ./serveur:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app_network

  frontend:
    build: ./client
    container_name: nginx_frontend
    restart: unless-stopped
    volumes:
      - ./client:/usr/share/nginx/html
    ports:
      - "80:80"
      - "3000:3000"  
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
