name: Build Cordova APK (Manual)

on:
  workflow_dispatch: 
    inputs:
      version:
        description: 'Version de l''application'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: sae4
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true 

      - name: Check if version apk exists with same version
        run: |
          if [ -f apk/pmdn-${{ github.event.inputs.version }}.apk ]; then
            echo "APK version ${{ github.event.inputs.version }} already exists"
            exit 1
          fi

      - name: Build APK with Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/client:/opt/src \
            hamdifourati/cordova-android-builder bash -c "
            cd /opt/src &&
            cordova platform add android &&
            cordova requirements &&
            cordova build
          "

      - name: Move APK to root directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/apk
          find client/platforms/android/app/build/outputs/apk/ -name "*.apk" -exec cp {} $GITHUB_WORKSPACE/apk/ \;
      
      - name: Configure Git login
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.USERNAME }}"

      - name: Commit and push APK
        run: |
          mv apk/app-debug.apk apk/pmdn-${{ github.event.inputs.version }}.apk
          git add apk/pmdn-${{ github.event.inputs.version }}.apk
          git commit -m ":rocket:(APK): Build APK version ${{ github.event.inputs.version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
